server:
  port: 9191
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/MultiTread?createDatabaseIfNotExist=true
    username: root
    password: Hoang01693113424
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        show_sql: true
        format_sql: true